# GitHub Action
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/metadata-syntax-for-github-actions

name: 'Jira Link Issue'
description: 'Link Jira issues as a comment'

branding:
  icon: message-circle
  color: blue

inputs:
  atlassian-domain:
    description: 'The domain of your Atlassian app'
    required: true

  github-token:
    description: 'The GitHub token for API access'
    required: false

runs:
  using: 'node12'
  main: 'src/index.js'
